# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ninfo.proto\"\x11\n\x0fNodeNameRequest\"\x80\x01\n\x10NodeNameResponse\x12$\n\x04name\x18\x01 \x01(\x0e\x32\x16.NodeNameResponse.Name\"F\n\x04Name\x12\r\n\tUNDEFINED\x10\x00\x12\r\n\tSHORTCAKE\x10\x01\x12\x08\n\x04\x45\x44\x45\x45\x10\x02\x12\n\n\x06OSHACK\x10\x03\x12\n\n\x06POMPOM\x10\x04\x32?\n\x0bInfoService\x12\x30\n\tname_info\x12\x10.NodeNameRequest\x1a\x11.NodeNameResponseb\x06proto3'
)



_NODENAMERESPONSE_NAME = _descriptor.EnumDescriptor(
  name='Name',
  full_name='NodeNameResponse.Name',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHORTCAKE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EDEE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OSHACK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POMPOM', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=92,
  serialized_end=162,
)
_sym_db.RegisterEnumDescriptor(_NODENAMERESPONSE_NAME)


_NODENAMEREQUEST = _descriptor.Descriptor(
  name='NodeNameRequest',
  full_name='NodeNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=31,
)


_NODENAMERESPONSE = _descriptor.Descriptor(
  name='NodeNameResponse',
  full_name='NodeNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeNameResponse.name', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODENAMERESPONSE_NAME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=162,
)

_NODENAMERESPONSE.fields_by_name['name'].enum_type = _NODENAMERESPONSE_NAME
_NODENAMERESPONSE_NAME.containing_type = _NODENAMERESPONSE
DESCRIPTOR.message_types_by_name['NodeNameRequest'] = _NODENAMEREQUEST
DESCRIPTOR.message_types_by_name['NodeNameResponse'] = _NODENAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeNameRequest = _reflection.GeneratedProtocolMessageType('NodeNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODENAMEREQUEST,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:NodeNameRequest)
  })
_sym_db.RegisterMessage(NodeNameRequest)

NodeNameResponse = _reflection.GeneratedProtocolMessageType('NodeNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODENAMERESPONSE,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:NodeNameResponse)
  })
_sym_db.RegisterMessage(NodeNameResponse)



_INFOSERVICE = _descriptor.ServiceDescriptor(
  name='InfoService',
  full_name='InfoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=164,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='name_info',
    full_name='InfoService.name_info',
    index=0,
    containing_service=None,
    input_type=_NODENAMEREQUEST,
    output_type=_NODENAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFOSERVICE)

DESCRIPTOR.services_by_name['InfoService'] = _INFOSERVICE

# @@protoc_insertion_point(module_scope)
