# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import info_pb2 as info__pb2


class InfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.name_info = channel.unary_unary(
                '/InfoService/name_info',
                request_serializer=info__pb2.NodeNameRequest.SerializeToString,
                response_deserializer=info__pb2.NodeNameResponse.FromString,
                )


class InfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def name_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'name_info': grpc.unary_unary_rpc_method_handler(
                    servicer.name_info,
                    request_deserializer=info__pb2.NodeNameRequest.FromString,
                    response_serializer=info__pb2.NodeNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def name_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InfoService/name_info',
            info__pb2.NodeNameRequest.SerializeToString,
            info__pb2.NodeNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
